c_compiler:
  - vs2022  # [win]
  - clang  # [unix]
c_compiler_version:  # [unix]
  - 19  # [unix]
cxx_compiler:
  - vs2022  # [win]
  - clangxx  # [unix]
cxx_compiler_version:  # [unix]
  - 19  # [unix]
