{% set name = "raspalib" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iRASPA/RASPA3/archive/v{{ version }}.tar.gz
  sha256: 74c602dc14153248023ae1894d0980ed3890a6cc24535ed03559f21bd527f67d

build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang-tools  # [unix]
    - llvm-tools  # [unix]
    - cmake
    - ninja
    - lld
    - libcxx-devel  # [osx]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - libcxx  # [osx]
    - libgomp  # [linux]
    - llvm-openmp  # [not linux]
    - libblas
    - liblapack
    - hdf5
    - zlib
    - openssl
    - libcurl
    - libaec
    - python
  run:
    - python

test:
  imports:
    - raspalib

about:
  home: https://github.com/iraspa/raspa3
  summary: 'Python library for raspa3 (a classical simulation package)'
  description: |
    RASPA is a software package for simulating adsorption and 
    diffusion of molecules in flexible nanoporous materials. 
    The code implements the latest state-of-the-art algorithms 
    for Molecular Dynamics and Monte Carlo in various ensembles 
    including symplectic/measure-preserving integrators, Ewald 
    summation, Configurational-Bias Monte Carlo, Continuous 
    Fractional Component Monte Carlo, and Reactive Monte Carlo.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://iraspa.github.io/RASPA3
  dev_url: https://github.com/iraspa/raspa3

extra:
  recipe-maintainers:
    - dubbelda
