{% set name = "raspalib" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iRASPA/RASPA3/archive/v{{ version }}.tar.gz
  sha256: 9cb460a8057f49abc387c13bc17e468db12df10f1a7620ef91fffc6ae324691a

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang-tools
    - llvm-tools
    - cmake
    - ninja
    - lld
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - libcxx  # [win]
    - libcxx-devel  # [not win]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - libcxx
    - libcxxabi  # [linux]
    - blas
    - lapack
    - libopenblas  # [linux]
    - hdf5
    - zlib
    - python
    - openssl
    - libcurl
    - libaec
  run:
    - libcxx
    - libcxxabi  # [linux]
    - python

test:
  imports:
    - raspalib

about:
  home: https://github.com/iraspa/raspa3
  summary: 'Python library for raspa3 (a classical simulation package)'
  description: |
    RASPA is a software package for simulating adsorption and 
    diffusion of molecules in flexible nanoporous materials. 
    The code implements the latest state-of-the-art algorithms 
    for Molecular Dynamics and Monte Carlo in various ensembles 
    including symplectic/measure-preserving integrators, Ewald 
    summation, Configurational-Bias Monte Carlo, Continuous 
    Fractional Component Monte Carlo, and Reactive Monte Carlo.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://iraspa.github.io/RASPA3
  dev_url: https://github.com/iraspa/raspa3

extra:
  recipe-maintainers:
    - dubbelda
